spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  # H2 console enabled (optional)
  h2:
    console:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    output:
      ansi:
        enabled: always

logging:
  level:
    org.hibernate.type: trace

file:
  upload:
    location: /Users/seyeon/Desktop